### ISSUE TITLE
Create a new project - Spring Boot CRUD - fails

### ISSUE THREAD

**Issue by ldimaggi** [snowdrop/spring-boot-crud-booster#10]
See details here:
https://github.com/fabric8-ui/fabric8-ui/issues/1668

**Comment by rdruss** [comment]
Related to an existing issue adopting the Fabric8 Jenkins Pipeline Library:
https://github.com/openshiftio/appdev-planning/issues/35

**Comment by metacosm** [comment]
Outdated.
