### ISSUE TITLE
Parity with node.js crud booster (Stock)

### ISSUE THREAD

**Issue by david-martin** [snowdrop/spring-boot-crud-booster#51]
The node.js crud booster has a Stock amount associated with Fruit.
This spring boot version of the crud booster should be the same (IMO) and include a Stock field, both in the db model & and in the webapp UI.

https://github.com/bucharest-gold/nodejs-rest-http-crud/blob/master/lib/api/fruits.js#L13-L15

**Comment by metacosm** [comment]
Is this Stock value part of the mission definition? /me needs to check

**Comment by metacosm** [comment]
Based https://github.com/fabric8-launcher/launcher-documentation/wiki/Mission:-Relational-Database-Backend, there doesn't seem to be a stock amount in the mission definition so, if anything, the node.js implementation should be fixed for consistency :wink:

**Comment by david-martin** [comment]
Thanks @metacosm 
I was unaware of the spec. Makes sense to leave it as is. Closing.
We can remove the dependency we have on there being a Stock field
